# -*- coding: utf-8 -*-
"""NBAVisualized.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGam1THDwNvJI9aPNu3rvnlZaJpdJmmv
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt


df1 = pd.read_csv('all_seasons.csv')

p1= sns.barplot(y=df1.loc[df1.season=='2018-19'].draft_year.value_counts().index,x=df1.loc[df1.season=='2017-18'].draft_year.value_counts()).set(
    title='Players Draft Years from the 2017-18 Season', xlabel='Number of Players', ylabel='Draft Year')

df = pd.read_csv('DraftNumberAverages.csv')

df.plot(x="draft_number", y=["Average_Pts", "Average_reb", "Average_ast"], kind="line")

plt.figure(figsize=(15,8))
ax = sns.lineplot(x='season',y='pts',data=df1.loc[df1['player_name'] == 'Manu Ginobili'], label='pts')
ax = sns.lineplot(x='season',y='ast',data=df1.loc[df1['player_name'] == 'Manu Ginobili'], label='ast')
ax = sns.lineplot(x='season',y='reb',data=df1.loc[df1['player_name'] == 'Manu Ginobili'], label='reb')
ax.set(ylabel = 'Average Stat', )
ax.legend()
plt.show()